const data = {
  products: [
    {
      _id: "1",
      name: "Nike Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: "4.5",
      countInStock: 10,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Puma Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 52,
      brand: "kenya West",
      rating: "4.5",
      countInStock: 10,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 145,
      brand: "Maria",
      rating: "4.5",
      countInStock: 10,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 127,
      brand: "Nike",
      rating: "4.5",
      countInStock: 15,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Nike Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 1204,
      brand: "Locasta",
      rating: "4.5",
      countInStock: 0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Nike Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 20,
      brand: "addidas",
      rating: "4.5",
      countInStock: 50,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "Nike Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 10,
      brand: "zara",
      rating: "4.5",
      countInStock: 0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "Nike Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 10,
      brand: "zara",
      rating: "1.5",
      countInStock: 30,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
