import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Shuvro",
      email: "shuvro@admin.com",
      password: bcrypt.hashSync("alena123", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Shuvro Das",
        logo: "../images/web.jpg",
        description: "MERN Stack Developer and Web Designer",
        rating: 5,
        numReviews: 150,
      },
    },
    {
      name: "Owner",
      email: "owner@admin.com",
      password: bcrypt.hashSync("alena123", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Kestopur Express",
        logo: "../images/meat.jpg",
        description: "Best Meat selller in kolkata",
        rating: 5,
        numReviews: 100,
      },
    },
    {
      name: "Tester",
      email: "tester@admin.com",
      password: bcrypt.hashSync("tester123", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Alena Groceries",
        logo: "../images/grocery.jpg",
        description: "ALena Groceries Item seller in kolkata",
        rating: 5,
        numReviews: 110,
      },
    },
  ],
  products: [
    {
      name: "Nike egwe  Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: "4.5",
      countInStock: 10,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Puma ggre Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 52,
      brand: "kenya West",
      rating: "4.5",
      countInStock: 10,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "hwfnweh fgewf Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 145,
      brand: "Maria",
      rating: "4.5",
      countInStock: 10,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "qwdwqjfewqfe gwe Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 127,
      brand: "Nike",
      rating: "4.5",
      countInStock: 15,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "qfqnwfq ewfew Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 1204,
      brand: "Locasta",
      rating: "4.5",
      countInStock: 0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "fnqfoi  wef fShirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 20,
      brand: "addidas",
      rating: "4.5",
      countInStock: 50,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "fwnefe ewfew Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 10,
      brand: "zara",
      rating: "4.5",
      countInStock: 0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "wfnweife df Shirts",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 10,
      brand: "zara",
      rating: "1.5",
      countInStock: 30,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "fnwifewf Genji",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 10,
      brand: "zara",
      rating: "1.5",
      countInStock: 30,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
